#!/usr/bin/env python3
"""Qwen3.8-Flash-Next 双机部署编排。

本文件只负责本地源码同步、远端命令转发和部署配置；SGLang 的实际实现
全部归当前仓库 dspark 子模块的 start.sh/stop.sh。
"""
import argparse
import os
import shlex
import socket
import subprocess
import sys
from pathlib import Path


def log(message, error=False):
    print(f"[{'FAIL' if error else 'INFO'}] {message}", file=sys.stderr if error else sys.stdout)


def parse_config(path):
    """解析本项目使用的扁平两级 YAML，避免部署入口新增第三方依赖。"""
    result, section = {}, None
    for raw in Path(path).read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if not raw.startswith(" ") and line.endswith(":"):
            section = line[:-1].strip()
            result[section] = {}
            continue
        if section is None or ":" not in line:
            raise ValueError(f"unsupported config line: {raw}")
        key, value = line.split(":", 1)
        value = value.strip()
        if " #" in value:
            value = value.split(" #", 1)[0].rstrip()
        result[section][key.strip()] = value.strip("\"'")
    return result


def run(argv, *, check=True, capture=False):
    log("$ " + " ".join(shlex.quote(item) for item in argv))
    return subprocess.run(argv, check=check, text=True, capture_output=capture)


def ssh(target, command, *, check=True, capture=False):
    return run(["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=10", "-o", "StrictHostKeyChecking=accept-new", target, command], check=check, capture=capture)


def shell_quote(value):
    return shlex.quote(str(value))


def constants(config):
    common, head, worker = config["common"], config["head"], config["worker"]
    return {
        "repo": common["repo"],
        "user": common["user"],
        "model": common["model"],
        "api_url": common["api_url"],
        "head": head["ssh"],
        "head_hostname": head["hostname"],
        "worker": worker["ssh"],
        "port": common.get("port", "8888"),
        "env": config.get("env", {}),
    }


def on_head(c):
    """head 本机直接执行，避免对自身发起 SSH 和 host-key 校验。"""
    return socket.gethostname() == c["head_hostname"] or (
        os.path.abspath(os.path.dirname(__file__)) == os.path.abspath(c["repo"])
    )


def sync_source(c, target):
    """本地源码是 SSOT；排除运行时缓存、日志和 Git 元数据。"""
    source = str(Path(__file__).resolve().parent) + "/"
    destination = f"{target}:{c['repo']}/"
    if target == c["head"] and on_head(c):
        run(["sudo", "mkdir", "-p", c["repo"]])
        run(["sudo", "chown", f"{c['user']}:{c['user']}", c["repo"]])
        log(f"source already at head:{c['repo']}; skip self-rsync")
        return
    else:
        ssh(target, f"sudo mkdir -p {shell_quote(c['repo'])} && sudo chown {shell_quote(c['user'])}:{shell_quote(c['user'])} {shell_quote(c['repo'])}")
    excludes = ["--exclude=.git", "--exclude=.cache", "--exclude=*.log", "--exclude=.sglang.pid"]
    run(["rsync", "-a", "--delete", *excludes, "-e", "ssh -o BatchMode=yes -o ConnectTimeout=10", source, destination])
    log(f"source synced -> {target}:{c['repo']}")


def remote_script(c, action, extra=()):
    script = f"{c['repo']}/dspark/start.sh"
    args = " ".join(shell_quote(item) for item in (action, *extra))
    command = f"cd {shell_quote(c['repo'])} && chmod +x dspark/start.sh dspark/stop.sh && {shell_quote(script)} {args}"
    if on_head(c):
        return run(["bash", "-lc", command])
    return ssh(c["head"], command)


def install_env(c, model=None):
    """严格从 config.yaml 的 env 节生成子模块环境，不合并旧文件。"""
    env = Path(__file__).resolve().parent / "dspark" / ".env"
    selected_model = model or c["model"]
    if selected_model != c["model"]:
        raise ValueError(f"model must equal configured local path: {c['model']}")
    values = dict(c["env"])
    values["MODEL_DIR"] = selected_model
    required = ("MODEL_DIR", "WORKER_SSH", "HEAD_CX7_IP", "WORKER_CX7_IP", "HEAD_CX7_IF", "WORKER_CX7_IF")
    missing = [key for key in required if key not in values]
    if missing:
        raise ValueError(f"config env missing required keys: {', '.join(missing)}")
    lines = ["# Generated by program.py from config.yaml; do not edit manually."]
    lines.extend(f"{key}={'' if value is None else value}" for key, value in values.items())
    env.write_text("\n".join(lines) + "\n", encoding="utf-8")
    log(f"generated {env}")


def cmd_install(c, model=None):
    install_env(c, model)
    sync_source(c, c["head"])
    sync_source(c, c["worker"])
    # 与 deepseek-flash 的 install 语义一致：install 是覆盖部署，始终先停旧容器。
    log("install is destructive to the running service: stopping existing containers")
    remote_script(c, "stop")
    remote_script(c, "serve")


def cmd_fetch(c, model=None):
    expected = "RadixArk/Qwen3.8-Flash-Next-NVFP4"
    if model and model != expected:
        raise ValueError(f"fetch only supports the configured model: {expected}")
    sync_source(c, c["head"])
    remote_script(c, "download")


def cmd_uninstall(c):
    remote_script(c, "stop", check=True)
    ssh(c["head"], "sudo systemctl disable --now qwen3.8-flash-next-head.service 2>/dev/null || true", check=False)
    ssh(c["worker"], "sudo systemctl disable --now qwen3.8-flash-next-worker.service 2>/dev/null || true", check=False)
    log("containers stopped; model and source retained")


def cmd_display(c, mode):
    target = "multi-user.target" if mode == "off" else "graphical.target"
    for node in (c["head"], c["worker"]):
        ssh(node, f"sudo systemctl set-default {target}")


def cmd_gen_env(c, output):
    install_env(c)
    source = Path(__file__).resolve().parent / "dspark" / ".env"
    content = source.read_text(encoding="utf-8")
    if output:
        Path(output).write_text(content, encoding="utf-8")
    else:
        sys.stdout.write(content)


def build_parser():
    parser = argparse.ArgumentParser(description="Qwen3.8-Flash-Next 双机部署编排")
    parser.add_argument("--config", default="/etc/qwen3.8-flash-next/config.yaml")
    sub = parser.add_subparsers(dest="command")
    sub.add_parser("install").add_argument("model", nargs="?")
    sub.add_parser("fetch").add_argument("model", nargs="?")
    sub.add_parser("uninstall")
    sub.add_parser("restart")
    sub.add_parser("stop")
    sub.add_parser("start")
    sub.add_parser("status")
    sub.add_parser("smoke")
    sub.add_parser("doctor")
    sub.add_parser("logs").add_argument("node", nargs="?", default="head")
    sub.add_parser("display").add_argument("mode", choices=("on", "off"))
    sub.add_parser("live_check")
    gen = sub.add_parser("gen-env")
    gen.add_argument("--output")
    sub.add_parser("help")
    return parser


def main(argv):
    parser = build_parser()
    args = parser.parse_args(argv[1:])
    if args.command in (None, "help"):
        parser.print_help()
        return 0
    config_path = Path(args.config)
    if not config_path.is_file():
        parser.error(f"missing config: {config_path}")
    try:
        c = constants(parse_config(config_path))
        if args.command == "install":
            return cmd_install(c, args.model) or 0
        if args.command == "fetch":
            return cmd_fetch(c, args.model) or 0
        if args.command == "uninstall":
            return cmd_uninstall(c) or 0
        if args.command == "display":
            return cmd_display(c, args.mode) or 0
        if args.command == "gen-env":
            return cmd_gen_env(c, args.output) or 0
        if args.command == "live_check":
            return remote_script(c, "status").returncode
        if args.command == "restart":
            remote_script(c, "stop")
            return remote_script(c, "serve").returncode
        if args.command == "logs":
            return remote_script(c, "logs", (args.node,)).returncode
        return remote_script(c, args.command).returncode
    except (subprocess.CalledProcessError, OSError, ValueError) as exc:
        log(str(exc), error=True)
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
